FROM wordpress:4

ENV WORDPRESS_VERSION 4.1.8
ENV WORDPRESS_UPSTREAM_VERSION 4.1.8
ENV WORDPRESS_SHA1 f3dc8f554312eeee5145c7eaaf85506e01a3d738

# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
RUN curl -o wordpress.tar.gz -sSL https://wordpress.org/wordpress-${WORDPRESS_UPSTREAM_VERSION}.tar.gz \
  && echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c - \
  && tar -xzf wordpress.tar.gz -C /usr/src/ \
  && rm wordpress.tar.gz \
  && chown -R www-data:www-data /usr/src/wordpress

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
