FROM wordpress:4

ENV WORDPRESS_VERSION 4.1.10
ENV WORDPRESS_UPSTREAM_VERSION 4.1.10
ENV WORDPRESS_SHA1 dae2e813e0f824c12d3c79df8f5783bc7fa9e312

# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
RUN curl -o wordpress.tar.gz -sSL https://wordpress.org/wordpress-${WORDPRESS_UPSTREAM_VERSION}.tar.gz \
  && echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c - \
  && tar -xzf wordpress.tar.gz -C /usr/src/ \
  && rm wordpress.tar.gz \
  && chown -R www-data:www-data /usr/src/wordpress

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
